project:
  type: website
  output-dir: _site
  preview:
    port: 8887
    browser: false
    navigate: false

execute:
  freeze: auto

filters:
- auto-dark
- surface-filename

website:
  title: "Manifesto For Change"
  site-url: https://manifestoforchange.org.uk
  repo-url: https://github.com/alexander-dast/manifestoforchange
  navbar: 
    left:
      - href: index.qmd
        text: Home
      - href: blog
        text: Blog
    right:
      - href: https://github.com/alexander-dast/manifestoforchange/
        icon: github

  sidebar:
    contents: 
      - section: Ideas & Policy
        contents: ideas-and-policy/*
      - section: Generic & Philosophy
        contents:
          philosophy/*
      - section: Project Approach
        contents: meta/*      
    style: docked

  draft-mode: unlinked 

metadata-files:
  - _drafts.yml

script-config:
  draft-directories:
    - ideas/
    - jobs/

format:
  html:
    include-in-header:
      text:
        <meta name="dc.relation.ispartof" content="manifestoforchange.org.uk">
        <meta name="dc.identifier" content="{{< meta site-post >}}">
    theme:
      light: simplex
    css: styles.css
    toc: true
    fig-format: svg
    fig-align: left
    fig-dpi: 300

comments:
  hypothesis:
    theme: classic

